version: "3.7"

services:

  spring:
    image: "tlsrl6427/yogiyo"
    ports:
      - "443:443"
    restart: always
    volumes:
      - /home/ec2-user/image-store:/image-store
      - /home/ec2-user/log:/log

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - /home/ec2-user/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - spring
    restart: always

  grafana:
    image: "grafana/grafana"
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - prometheus
